tatumio/tatum-js

src/index.ts
=> export nft functions

src/model/request/index.ts
=> fix: missing celo export

packages/tatum-ada/src/wallet/wallet.ts, packages/tatum-bch/src/wallet/wallet.ts, packages/tatum-bnb/src/wallet/wallet.ts, packages/tatum-bnb/yarn.lock, packages/tatum-bsc/src/wallet/wallet.ts, packages/tatum-celo/src/wallet/wallet.ts, packages/tatum-core/src/wallet/wallet.ts, packages/tatum-doge/src/wallet/wallet.ts, packages/tatum-eth/src/wallet/wallet.ts, packages/tatum-one/src/wallet/wallet.ts, packages/tatum-polygon/src/wallet/wallet.ts, packages/tatum-scrypta/src/wallet/wallet.ts, packages/tatum-vet/src/wallet/wallet.ts, packages/tatum-xdc/src/wallet/wallet.ts, packages/tatum-xlm/src/wallet/wallet.ts, packages/tatum-xlm/yarn.lock, packages/tatum-xrp/package.json, packages/tatum-xrp/src/wallet/wallet.spec.ts, packages/tatum-xrp/src/wallet/wallet.ts, packages/tatum-xrp/yarn.lock
I have changed some return objects as discussed earlier. Please review these changes.
=> feature/submodule: unify wallet interfaces

packages/tatum-btc/package.json
Added missing `hdkey` dependency
=> Added missing btc dependencies

packages/tatum-btc/src/offchain/bitcoin.ts, packages/tatum-btc/src/offchain/kms.ts, packages/tatum-btc/src/transaction/bitcoin.ts
=> Fix btc imports

packages/tatum-btc/package.json, packages/tatum-doge/package.json
Added missing depndencies for doge and btc.
=> Add missing dependencies

packages/tatum-bsc/src/fungible/index.ts, packages/tatum-bsc/src/nft/marketplace/auction.ts, packages/tatum-celo/src/fungible/index.ts, packages/tatum-kcc/src/fungible/index.ts, packages/tatum-one/src/fungible/index.ts, packages/tatum-one/src/nft/marketplace/auction.ts, packages/tatum-polygon/src/fungible/index.ts, packages/tatum-tron/package.json, yarn.lock
I fixed imports in others as well. A bit off-topick of this ticket, but I did.
=> Fixed imports and dependencies in tron one

packages/tatum-core/src/multiToken/index.ts, packages/tatum-eth/src/index.ts, packages/tatum-eth/src/multiToken/index.ts, packages/tatum-one/src/index.ts, packages/tatum-one/src/multiToken/index.ts, packages/tatum-polygon/src/index.ts, packages/tatum-polygon/src/multiToken/index.ts
fix getMultiTokenTransaction return type in tatum-core module.
add getMultiTokenTransaction into CELO, ETH, POLYGON blockchain
=> Add missing implementation - Get multi-token transaction

package.json, src/blockchain/qtum.ts, src/wallet/custodial.ts
Fixed API calls in tatum-js. This is community bug fix. Should be merged into master.
=> Community bug/#81 fix api calls

package.json, src/model/request/Currency.ts
Added new GLMR currency into tatum-js.
=> Moonbeam integration add currency

examples/algo-example/src/app/algo.tx.example.ts, examples/bsc-example/src/app/bsc.tx.example.ts, examples/celo-example/src/app/celo.tx.example.ts, examples/eth-example/src/app/eth.tx.example.ts, examples/kcs-example/src/app/kcs.tx.example.ts, examples/klaytn-example/src/app/klaytn.tx.example.ts, examples/one-example/src/app/one.tx.example.ts, examples/polygon-example/src/app/polygon.tx.example.ts, examples/tron-example/src/app/tron.tx.example.ts, packages/blockchain/algo/src/lib/algo.sdk.ts, packages/blockchain/algo/src/lib/services/algo.tx.ts, packages/blockchain/bsc/src/lib/__tests__/bsc.tx.spec.ts, packages/blockchain/bsc/src/lib/bsc.sdk.ts, packages/blockchain/celo/src/lib/__tests__/celo.tx.spec.ts, packages/blockchain/celo/src/lib/celo.sdk.ts, packages/blockchain/eth/src/lib/__tests__/eth.tx.spec.ts, packages/blockchain/eth/src/lib/eth.sdk.ts, packages/blockchain/kcs/src/lib/__tests__/kcs.tx.spec.ts, packages/blockchain/kcs/src/lib/kcs.sdk.ts, packages/blockchain/klaytn/src/lib/__tests__/klaytn.tx.spec.ts, packages/blockchain/klaytn/src/lib/sdk-klaytn.ts, packages/blockchain/one/src/lib/__tests__/one.tx.spec.ts, packages/blockchain/one/src/lib/one.sdk.ts, packages/blockchain/polygon/src/lib/__tests__/polygon.tx.spec.ts, packages/blockchain/polygon/src/lib/polygon.sdk.ts, packages/blockchain/tron/src/lib/services/tron.custodial.ts, packages/blockchain/tron/src/lib/services/tron.tx.ts, packages/blockchain/tron/src/lib/tron.sdk.ts
Hotfix for last PR that was approved before CI which failed.
=> Feature/plt 397 sdk paths [hotfix]

src/wallet/address.spec.ts, src/wallet/address.ts
Adding bech32 BTC wallet generation to v1 sdk
v2 https://github.com/tatumio/tatum-js/pull/465
=> PLT-108 - add bech32 btc address generation to v1

package.json
=> PLT-108 - bump version for release

package.json, src/model/request/Currency.ts
=> TT-533 - add FTM

package.json, packages/blockchain/one/src/lib/services/one.gasPump.ts, packages/blockchain/one/src/lib/services/one.tx.ts
- Activation flow for one gas pump
=> Fix one error

examples/xlm-example/README.md, examples/xlm-example/src/app/xlm.balance.example.ts, examples/xlm-example/src/app/xlm.blockchain.example.ts, examples/xlm-example/src/app/xlm.tx.example.ts, examples/xlm-example/src/app/xlm.tx.trustline.example.ts, examples/xlm-example/src/app/xlm.virtualAccount.example.ts, examples/xlm-example/src/index.ts
This is the first README that I proofread.
If my changes are OK, I will apply them to all the other READMEs.
@samuelsramko - ready for your review, thank you.
=> TT-2959: Stellar README and examples

CHANGELOG.md, package.json
=> ALL-43 - release final 1.0.0

.github/workflows/build.yml, .github/workflows/release-pr.yaml, README.md, examples/browser/package.json, examples/browser/yarn.lock, examples/nextjs/package.json, examples/nextjs/yarn.lock, examples/typescript/package.json, examples/typescript/yarn.lock
=> Update examples package.json

.github/workflows/build.yml, .github/workflows/release-pr.yaml, README.md, examples/browser/package.json, examples/browser/yarn.lock, examples/nextjs/package.json, examples/nextjs/yarn.lock, examples/typescript/package.json, examples/typescript/yarn.lock
=> Update examples package

package.json, packages/api-client/src/generated/services/BitcoinService.ts, packages/api-client/src/generated/services/LitecoinService.ts, packages/shared/blockchain/btc-based/src/lib/nested/btc-based.tx.ts
=> Add tx type fetch btc and ltc txs by address

package.json, packages/blockchain/tron/src/lib/services/tron.trc20.ts
=> ALL-1134 - Fix BUSD send

CHANGELOG.md, package.json, src/e2e/tatum.notification.spec.ts, src/e2e/tatum.rpc.spec.ts, src/e2e/tatum.spec.ts, src/service/rpc/rpc.ts, src/service/tatum/tatum.dto.ts, src/service/tatum/tatum.ts, src/util/constant.ts, src/util/utils.shared.spec.ts
=> Add support for multiple static urls for Open Network

package.json, packages/blockchain/tron/src/lib/services/tron.trc20.ts
=> ALL-1134 - Fix Tron trx20 send

CHANGELOG.md, package.json, src/e2e/tatum.rpc.spec.ts, src/service/notification/notification.ts, src/service/notification/subscribe.ts, src/service/rpc/rpc.ts, src/service/tatum/tatum.ts
=> added fastest URL

examples/docs/get-balance-eth/app.js, examples/docs/get-balance-eth/index.html, examples/docs/get-balance-eth/package-lock.json, examples/docs/get-balance-eth/package.json
=> ALL-1438 - Get balance example app

src/util/util.shared.ts
Adding a simple util function to be used in the upcoming new RPC interfaces.
=> ALL-1431 Add simple camelToSnakeCase util function

CHANGELOG.md, package.json, src/dto/Network.ts, src/dto/rpc/SolanaRpcSuite.ts, src/dto/rpc/index.ts, src/e2e/tatum.rpc.solana.spec.ts, src/service/rpc/engine/SolanaRpc.ts, src/service/rpc/engine/index.ts, src/util/util.shared.ts
Add interface for interaction with Solana JSON RPC. Supported methods are from this link https://docs.solana.com/api/http
=> ALL-1374 Add solana rpc

CHANGELOG.md, package.json, src/dto/rpc/SolanaRpcSuite.ts
Add comments to input params for Solana RPC
=> ALL-1374 Add comments to input params for Solana RPC

CHANGELOG.md, package.json, src/dto/rpc/SolanaRpcSuite.ts, src/dto/rpc/XrpRpcSuite.ts, src/e2e/tatum.rpc.solana.spec.ts
Add documentation for XRP RPC and Solana RPC.
=> ALL-1496 Add docs for XRP and Solana RPC

CHANGELOG.md, package.json, src/dto/rpc/TronRpcSuite.ts, src/service/rpc/engine/TronRpc.ts
Added jsdoc for tron rpc, fixed wrong param names
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
=> ALL-1638: added tron rpc docs, fixed method params

CHANGELOG.md, README.md, package.json, src/e2e/tatum.rates.spec.ts, src/service/rate/index.ts, src/service/rate/rates.dto.ts, src/service/rate/rates.ts, src/service/tatum/tatum.ts
Added `rates` submodule including `getCurrentRate` and `getCurrentRateBatch` methods for obtaining current fiat/crypto exchange rates.
=> ALL-1456: add rates submodule

CHANGELOG.md, package.json, src/e2e/e2e.util.ts, src/e2e/tatum.fee.spec.ts, src/service/address/address.ts, src/service/rpc/generic/LoadBalancerRpc.ts
=> ALL-1506 - Fix tests

CHANGELOG.md, package.json, src/e2e/rpc/tatum.rpc.tron.spec.ts, src/service/rpc/TronRpc.ts, src/util/error.ts, src/util/util.shared.ts
=> ALL-1885 - improve Tron RPC calls error handling

CHANGELOG.md, package.json, src/connector/tatum.connector.ts, src/service/rpc/generic/LoadBalancerRpc.ts
=> ALL-1948 Added JSON stringify to see error message of Load Balancer

package.json, packages/blockchain/tron/src/lib/services/tron.virtualAccount.ts
Customer discovered error during transfer of native token on Tron from virtual account to blockchain. Transaction in the virtual account service was signed and broadcasted instead of just prepared. That lead to broadcasting the transaction twice and failed during the second time.
=> ALL-2222 Tron transfer issue

package.json, packages/blockchain/doge/src/lib/__tests__/doge.tx.spec.ts, packages/blockchain/doge/src/lib/doge.sdk.errors.ts, packages/blockchain/doge/src/lib/doge.sdk.tx.ts, packages/shared/abstract-sdk/src/lib/errors.abstract.sdk.ts, packages/shared/testing/btc-based/src/lib/old-btc-based.tx.test-factory.ts
=> ALL-2244 Doge fixes, better handling of dust amount

package.json, packages/blockchain/doge/src/lib/doge.sdk.errors.ts
=> ALL-2062 Doge too large fee error code

CHANGELOG.md, package.json, src/e2e/rpc/evm.e2e.utils.ts, src/e2e/rpc/tatum.rpc.flare.spec.ts, src/e2e/rpc/tatum.rpc.polygon.spec.ts, src/service/rpc/generic/LoadBalancerRpc.ts
=> ALL-2331 Change 'No active node' error msg inside RPC SDK

CHANGELOG.md, package.json, src/e2e/rpc/evm.e2e.utils.ts, src/service/tatum/tatum.ts
=> ALL-2230 - Added destroy to global object

CHANGELOG.md, package.json, src/util/error.ts
=> ALL-2054 - Add error log link

README.md, src/e2e/rpc/rpc.e2e.utils.ts, src/e2e/rpc/tatum.rpc.optimism.spec.ts
=> Update README.md - add more links and docs

CHANGELOG.md, package.json, src/connector/tatum.connector.ts, src/e2e/rpc/evm.e2e.utils.ts, src/e2e/rpc/rpc.e2e.utils.ts, src/e2e/rpc/tatum.rpc.optimism.spec.ts, src/service/rpc/generic/LoadBalancerRpc.ts, src/util/util.shared.ts
=> ALL-2377 Fix loadbalancer & document status pages

src/e2e/rpc/tatum.rpc.bitcoin.spec.ts, src/e2e/rpc/tatum.rpc.ethereum.spec.ts, src/e2e/tatum.address.spec.ts, src/e2e/tatum.fee.spec.ts, src/e2e/tatum.rates.spec.ts, src/e2e/tatum.spec.ts
=> Fix Tests destroy

CHANGELOG.md, package.json
=> Revert "Move node-fetch from devDep to Dep"

CHANGELOG.md, package.json, src/e2e/rpc/tatum.rpc.eon.spec.ts, src/e2e/rpc/tatum.rpc.optimism.spec.ts, src/e2e/tatum.address.spec.ts, src/util/util.shared.ts
=> ALL-2513 Fix undici dep

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancerRpc.ts
=> ALL-2518 Fix process is undefined on the pure browser

package.json, tsconfig.base.json, workspace.json
Add tezos to workspace in order to publish it to npm
=> ALL-1479 Publish Tezos lib

CHANGELOG.md, package.json, src/util/constant.ts
=> ALL-2533 Route to v4

package.json, packages/blockchain/tezos/src/index.ts
=> ALL-1479 tezos export

package.json, packages/blockchain/tezos/src/lib/__tests__/tezos.e2e.blockchain.spec.ts, packages/blockchain/tezos/src/lib/services/tezos.tzip.ts
Small adjustments to a Tezos nft mint
=> ALL-1479-tezos-mint

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancerRpc.ts
=> ALL-2574 - Add SSRF check to initRemoteHosts method in LoadBalancerRpc

package.json, packages/blockchain/tezos/src/lib/__tests__/tezos.e2e.blockchain.spec.ts, packages/blockchain/tezos/src/lib/services/tezos.tzip.ts
Add functions for estimating fees for contract deploy, mint and transfer on Tezos network
=> ALL-1479 Estimate Tezos fees

package.json, packages/api-client/src/lib/models/Currency.ts
Add Horizen currency ZEN to the existing enum
=> ALL-2131 Add Horizen currency

package.json, src/model/request/Currency.ts
=> ALL-2131 Add ZEN currency

CHANGELOG.md, package.json, src/dto/rpc/EvmBasedRpcInterface.ts, src/e2e/rpc/tatum.rpc.ethereum.spec.ts, src/service/rpc/evm/AbstractEvmRpc.ts
Add functions to EVM rpc interface: getTokenTotalSupply, getTokenCap, supportsInterfaceERC1155
=> ALL-2135 Extend EVM RPC interface

CHANGELOG.md, package.json, src/e2e/rpc/utxo.e2e.utils.ts, src/service/rpc/utxo/AbstractUtxoRpc.ts
=> ALL-2637 - UTXO estimateSmartFee optional estimateMode param

package.json, packages/blockchain/tezos/src/lib/__tests__/tezos.e2e.blockchain.spec.ts, packages/blockchain/tezos/src/lib/contracts/tzip12.ts, packages/blockchain/tezos/src/lib/services/tezos.tzip.ts
Add support for multiple minters for Tezos NFTs. Deploy contract with a default minter, add or remove a minter. Contains changes for a Tzip-12 contract.
=> ALL-1479 Add support for multiple minters for Tezos tokens

CHANGELOG.md, package.json, src/util/util.shared.ts
=> ALL-2673 - Fix loadbalancer to work without api key

CHANGELOG.md, package.json, src/e2e/tatum.address.spec.ts, src/service/tatum/tatum.ts, src/util/util.shared.ts
=> ALL-2483 - Update Horizen class

CHANGELOG.md, package.json, src/dto/rpc/AbstractJsonRpcInterface.ts, src/service/rpc/AbstractTronRpc.ts, src/service/rpc/evm/EvmArchiveLoadBalancerRpc.ts, src/service/rpc/evm/EvmLoadBalancerRpc.ts, src/service/rpc/evm/TronLoadBalancerRpc.ts, src/service/rpc/evm/TronRpc.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/rpc/utxo/UtxoLoadBalancerRpc.ts, src/service/rpc/utxo/UtxoRpc.ts
=> Expose rpc node url

CHANGELOG.md, README.md, package.json, src/e2e/tatum.nft.spec.ts, src/service/nft/nft.dto.ts, src/service/nft/nft.ts, src/service/tatum/tatum.ts
Add support for deploying contracts on Tezos blockchain.
=> ALL-1479 Create collection for Tezos

CHANGELOG.md, package.json, src/e2e/rpc/evm/tatum.rpc.ethereum.spec.ts, src/service/rpc/evm/EvmArchiveLoadBalancerRpc.ts
=> fix eth_getLogs method

CHANGELOG.md, package.json, src/service/nft/nft.dto.ts
=> Fixed 'tokenType' field to 'type' in Non-Fungible Token

.github/workflows/main.yml, README.md, documentation/blockchain/marketplace/auction.md, documentation/blockchain/marketplace/marketplace.md, documentation/blockchain/nft/nft.md, package.json, src/blockchain/README.md, src/ledger/README.md, src/nft/README.md, src/offchain/README.md, src/security/README.md, src/transaction/README.md, src/wallet/README.md
This reverts commit 964828ec
New version and tagged publish of v1
=> Revert "ALL-2604 New package name - @tatumio/tatum-v1 (#919)"

packages/blockchain/eon/.babelrc, packages/blockchain/eon/.eslintrc.json, packages/blockchain/eon/jest.config.ts, packages/blockchain/eon/package.json, packages/blockchain/eon/project.json, packages/blockchain/eon/src/index.ts, packages/blockchain/eon/src/lib/eon.sdk.spec.ts, packages/blockchain/eon/src/lib/eon.sdk.ts, packages/blockchain/eon/src/lib/services/eon.tx.ts, packages/blockchain/eon/src/lib/services/eon.web3.ts, packages/blockchain/eon/tsconfig.json, packages/blockchain/eon/tsconfig.lib.json, packages/blockchain/eon/tsconfig.spec.json, tsconfig.base.json, workspace.json
Add package for Horizen Eon, support for NFT deploy. Mint and transfer will be in next PR
=> ALL-2699 Add support for Horizen Eon NFT deploy

package.json, packages/blockchain/eon/src/lib/eon.sdk.ts, packages/blockchain/eon/src/lib/services/eon.tx.ts
Add functions for mint, transfer, burn, add minter
=> All-2699 Add nft support for Horizen EON

CHANGELOG.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/service/tatum/tatum.ts, src/util/constant.ts, src/util/util.shared.ts
=> #938 ALL-2668 Add Horizen Eon Gobi and Chiliz Rpc support

README.md
=> ALL-2863 - Updated Chiliz and Gobi to readme

package.json, packages/blockchain/tron/src/lib/services/tron.custodial.ts
Fix custodial wallet transfer for Tron
=> ALL-2897 Fix custodial wallet transfer for Tron

CHANGELOG.md, README.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts
=> ALL-2607 - Add Rpc Ethereum Classic support

CHANGELOG.md, README.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/utxo/tatum.rpc.doge.spec.ts, src/e2e/rpc/utxo/utxo.e2e.utils.ts, src/e2e/rpc/utxo/utxo.rpc.spec.ts, src/service/tatum/tatum.ts, src/util/util.shared.ts
=> ALL-2609 - Add Rpc ZCash support

CHANGELOG.md, package.json, src/dto/Network.ts, src/dto/rpc/NativeEvmBasedRpcInterface.ts, src/e2e/rpc/evm/evm.e2e.utils.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/evm/tatum.rpc.klay.spec.ts, src/service/rpc/evm/AbstractNativeEvmRpc.ts, src/service/rpc/evm/EvmArchiveLoadBalancerRpc.ts, src/service/rpc/evm/EvmUtils.ts, src/service/rpc/evm/NativeEvmArchiveLoadBalancerRpc.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/tatum/tatum.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-3003 Add Klaytn rpc support

CHANGELOG.md, package.json, src/dto/Network.ts, src/e2e/rpc/other/tatum.rpc.eos.spec.ts, src/e2e/rpc/utxo/utxo.e2e.utils.ts, src/e2e/rpc/utxo/utxo.rpc.spec.ts
=> ALL-2669 Add Support for Bitcoin Cash

README.md
Update docs links for rpc status pages and list.json
=> Update docs links for rpc

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancer.ts
Updated logging for loadbalancer
=> ALL-2673 Updated loadbalancer logging

CHANGELOG.md, package.json, src/service/tatum/tatum.ts
Add walletProvider to TatumSdkChain so any chain can support wallet extensions
=> ALL-3037 Add wallet provider for Tezos

README.md
=> ALL-2965 Add faucet links to README

CHANGELOG.md, package.json, src/e2e/tatum.spec.ts, src/util/tatum.utils.ts
Provides better experience to users by either returning usable result of throwing meaningful error.
=> `TatumUtils` better error messages and types

CHANGELOG.md, README.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts
=> ALL-2952 Add Celo network support

CHANGELOG.md, package.json, src/dto/Network.ts, src/dto/rpc/UtxoBasedRpcSuite.ts, src/e2e/rpc/utxo/tatum.rpc.bch.spec.ts, src/e2e/rpc/utxo/utxo.e2e.utils.ts, src/service/rpc/utxo/AbstractUtxoRpcEstimateFee.ts, src/service/rpc/utxo/UtxoLoadBalancerRpcEstimateFee.ts, src/service/rpc/utxo/UtxoRpcEstimateFee.ts, src/service/tatum/tatum.utxo.ts, src/util/util.shared.ts
Add estimatefee to the Bitcoin Cash rpc.
=> ALL-3150 - add bch estimatefee method

CHANGELOG.md, package.json, src/dto/Network.ts, src/dto/rpc/BnbRpcSuite.ts, src/e2e/rpc/other/tatum.rpc.bnb.spec.ts, src/service/rpc/other/AbstractBnbRpc.ts, src/service/rpc/other/BnbLoadBalancerRpc.ts, src/service/tatum/tatum.other.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-3155 Add BNB support

CHANGELOG.md, package.json, src/service/rpc/evm/BeaconV1EvmRpc.ts, src/service/rpc/evm/EvmArchiveLoadBalancerRpc.ts, src/service/rpc/evm/EvmBeaconArchiveLoadBalancerRpc.ts, src/service/rpc/evm/EvmLoadBalancerRpc.ts, src/service/rpc/evm/NativeEvmArchiveLoadBalancerRpc.ts, src/service/rpc/evm/TronLoadBalancerRpc.ts, src/service/rpc/other/BnbLoadBalancerRpc.ts, src/service/rpc/other/EosLoadBalancerRpc.ts, src/service/rpc/other/SolanaLoadBalancerRpc.ts, src/service/rpc/other/XrpLoadBalancerRpc.ts, src/service/rpc/utxo/UtxoLoadBalancerRpc.ts, src/service/rpc/utxo/UtxoLoadBalancerRpcEstimateFee.ts, yarn.lock
=> ALL-3259 - Fix LB import

CHANGELOG.md, README.md, package.json, src/dto/Network.ts, src/dto/rpc/TezosRpcSuite.ts, src/dto/rpc/tezos.types.ts, src/e2e/rpc/other/tatum.rpc.solana.spec.ts, src/e2e/rpc/other/tatum.rpc.tezos.spec.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/rpc/other/AbstractTezosRpc.ts, src/service/rpc/other/TezosLoadBalancerRpc.ts, src/service/tatum/tatum.other.ts, src/util/util.shared.ts
=> ALL-3155 Add Tezos support

CHANGELOG.md, package.json, src/dto/GetI.ts, src/dto/PostI.ts, src/dto/rpc/TezosRpcSuite.ts, src/dto/shared.dto.ts, src/e2e/rpc/other/tatum.rpc.tezos.spec.ts, src/e2e/tatum.faucet.spec.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/rpc/other/AbstractTezosRpc.ts, src/service/rpc/other/EosLoadBalancerRpc.ts, src/service/rpc/other/TezosLoadBalancerRpc.ts, src/util/util.shared.ts
=> ALL-3134 Update Tezos methods

CHANGELOG.md, package.json, src/dto/rpc/AlgorandIndexerRpcSuite.ts
=> ALL-3235 Fixed Algorand ApplicationSearchParams to camel case

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancer.ts
Fixes lb issue with fallback on archiv nodes.
=> ALL-3458 Fix lb archive fallback

package.json, packages/shared/blockchain/btc-based/src/lib/nested/btc-based.tx.ts
apply fee and balance validations to signatureId based BTC transactions
=> ALL-3518 - apply validations to signatureId based BTC transactions

README.md
=> Replaced an example code in doc with the appropriate variable

CHANGELOG.md, package.json, src/dto/rpc/StellarRpcSuite.ts, src/e2e/rpc/other/tatum.rpc.stellar.spec.ts, src/service/rpc/other/AbstractStellarRpc.ts
=> ALL-3288 Fix Stellar get strict

package.json, packages/shared/core/src/lib/derivation-path.common.ts, packages/shared/core/src/lib/http.common.ts, packages/shared/core/src/lib/models/Blockchain.ts, packages/shared/core/src/lib/models/BlockchainCurrencyMapping.ts
=> ALL-4358 Add FLR to blockchain

package.json, packages/automation/src/generators/blockchain-evm/files/src/lib/__tests__/__name__.blockchain.spec.ts__template__, packages/blockchain/flare/src/lib/__tests__/flare.blockchain.spec.ts
=> ALL-4358 Fix Flare Tests

CHANGELOG.md, package.json, src/e2e/rpc/other/tatum.rpc.solana.spec.ts, src/e2e/rpc/other/tatum.rpc.stellar.spec.ts, src/service/rpc/other/SolanaArchiveLoadBalancerRpc.ts, src/util/util.shared.ts
Added Solana lb for archive methods
=> ALL-4448 - Add Solana lb for archive methods

CHANGELOG.md, README.md, package.json, src/service/rpc/evm/EvmUtils.spec.ts, src/service/rpc/evm/EvmUtils.ts
=> ALL-4448 - Update archive conditions

CHANGELOG.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts
=> ALL-4379 - Add Cronos & Fantom

package.json, packages/blockchain/solana/src/lib/__tests__/solana.tx.spec.ts, packages/blockchain/solana/src/lib/services/solana.tx.ts
=> ALL-5473 - Fix SOL duplicate txID

package.json, packages/blockchain/solana/src/lib/__tests__/solana.tx.spec.ts, packages/blockchain/solana/src/lib/services/solana.marketplace.ts, packages/blockchain/solana/src/lib/services/solana.nft.ts, packages/blockchain/solana/src/lib/services/solana.spl.ts, packages/blockchain/solana/src/lib/services/solana.tx.ts, packages/blockchain/solana/src/lib/services/solana.utils.ts
Fix Solana confirm transaction with custom retry
=> ALL-5473 - Fix Solana confirm transaction with custom retry

CHANGELOG.md, package.json, src/dto/Network.ts, src/e2e/rpc/other/tatum.rpc.stellar.spec.ts, src/service/tatum/tatum.dto.ts, src/service/tatum/tatum.ts, src/util/util.shared.ts
Adding support for simplified way of configuring api key without specifying version.
=> ALL-5273 Extend api key config options

CHANGELOG.md, package.json, src/dto/Currency.ts, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/service/tatum/tatum.evm.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-4820 - Added BASE RPC Support

CHANGELOG.md, package.json, src/connector/tatum.connector.ts, src/dto/AddressEventNotificationChain.ts, src/dto/Network.ts, src/dto/rpc/EvmBasedRpcInterface.ts, src/e2e/e2e.constant.ts, src/e2e/e2e.util.ts, src/e2e/rpc/evm/eth/tatum.rpc.beacon.spec.ts, src/e2e/rpc/other/tatum.rpc.xrp.spec.ts, src/e2e/tatum.notification.spec.ts, src/service/rpc/evm/AbstractBeaconV1EvmRpc.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/tatum/tatum.evm.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-4895 - Add Cronos subscriptions

CHANGELOG.md, package.json, src/dto/rpc/SolanaRpcSuite.ts, src/service/rpc/other/AbstractSolanaRpc.ts
Fix return type for solana getFeeForMessage
=> ALL-5774 Fix return type for solana getFeeForMessage

CHANGELOG.md, package.json, src/dto/AddressEventNotificationChain.ts, src/dto/Network.ts, src/e2e/e2e.constant.ts, src/e2e/e2e.util.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/other/tatum.rpc.solana.spec.ts, src/service/tatum/tatum.evm.ts, src/util/util.shared.ts
=> ALL-5628 - Add Base subscriptions

CHANGELOG.md, package.json, src/connector/tatum.connector.ts, src/dto/Currency.ts, src/dto/Network.ts, src/dto/rpc/KadenaRpcSuite.ts, src/dto/shared.dto.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/other/kadena.rpc.spec.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/rpc/other/AbstractKadenaRpc.ts, src/service/rpc/other/KadenaLoadBalancerRpc.ts, src/service/tatum/tatum.other.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-5502 - Add Kadena L0

CHANGELOG.md, package.json, src/dto/Currency.ts, src/dto/Network.ts, src/e2e/rpc/other/tatum.rpc.cosmos.rosetta.spec.ts, src/e2e/rpc/other/tatum.rpc.xrp.spec.ts, src/e2e/tatum.notification.spec.ts, src/service/tatum/tatum.other.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-5086 - Add Cosmos RPC

CHANGELOG.md, README.md, package.json, src/dto/Currency.ts, src/dto/Network.ts, src/dto/rpc/IotaRpcSuite.ts, src/e2e/rpc/evm/tatum.rpc.iota.spec.ts, src/e2e/rpc/other/tatum.rpc.solana.spec.ts, src/service/rpc/evm/AbstractBeaconV1EvmRpc.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/rpc/other/AbstractAlgorandAlgodRpc.ts, src/service/rpc/other/AbstractAlgorandIndexerRpc.ts, src/service/rpc/other/AbstractIotaRpc.ts, src/service/rpc/other/AbstractKadenaRpc.ts, src/service/rpc/other/AbstractStellarRpc.ts, src/service/rpc/other/AbstractTezosRpc.ts, src/service/rpc/other/IotaLoadBalancerRpc.ts, src/service/tatum/tatum.other.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-5089 Add IOTA rpc

src/fungible/index.ts, src/multiToken/index.ts, src/nft/marketplace/auction.ts, src/nft/marketplace/listing.ts, src/nft/nft.ts, src/wallet/custodial.ts
Added forward slashes to URLs to make them consistent with all of the other and make them work.
=> V1 slashes fix

package.json, src/fungible/index.ts, src/multiToken/index.ts, src/nft/marketplace/auction.ts, src/nft/marketplace/listing.ts, src/nft/nft.ts, src/wallet/custodial.ts
Bump up the version because I forgot to do it earlier
=> chore: bump up version

CHANGELOG.md, package.json, src/dto/Network.ts
=> ALL-6564: enable amoy data-api

CHANGELOG.md, package.json, src/connector/tatum.connector.ts, src/dto/Network.ts, src/e2e/rpc/other/tatum.rpc.electrs.spec.ts, src/e2e/rpc/other/tatum.rpc.iota.spec.ts, src/service/rpc/evm/AbstractTronRpc.ts, src/service/rpc/evm/TronLoadBalancerRpc.ts, src/service/rpc/evm/TronRpc.ts, src/service/rpc/generic/LoadBalancer.ts, src/service/rpc/other/AbstractEosRpc.ts, src/service/rpc/other/AbstractKadenaRpc.ts, src/service/rpc/other/AbstractStellarRpc.ts, src/service/rpc/other/IotaRpc.ts, src/service/tatum/tatum.other.ts, src/service/tatum/tatum.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-7216 - Add electrs & iota, rename rostrum

CHANGELOG.md, package.json, src/dto/Network.ts, src/dto/rpc/CosmosRpcSuite.ts, src/e2e/rpc/other/tatum.rpc.cosmos.rosetta.spec.ts, src/e2e/rpc/other/tatum.rpc.kadena.spec.ts, src/service/rpc/other/AbstractCardanoRpc.ts, src/service/rpc/other/AbstractCosmosRpc.ts, src/service/rpc/other/CosmosLoadBalancerRpc.ts, src/service/tatum/tatum.other.ts, src/util/util.shared.ts
=> ALL-7315 - Add Cosmos grpc

package.json
=> ALL-7351: version bump

CHANGELOG.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/other/tatum.rpc.electrs.spec.ts, src/e2e/rpc/other/tatum.rpc.rostrum.spec.ts, src/e2e/rpc/other/tatum.rpc.stellar.spec.ts, src/e2e/rpc/utxo/utxo.rpc.spec.ts, src/e2e/tatum.fee.spec.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-7026 - Add Rostrum & Electrs testnet

CHANGELOG.md, package.json, src/dto/Currency.ts, src/dto/Network.ts, src/dto/rpc/CasperRpcSuite.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/other/tatum.rpc.casper.spec.ts, src/e2e/rpc/other/tatum.rpc.tron.spec.ts, src/e2e/tatum.fee.spec.ts, src/e2e/tatum.rates.spec.ts, src/service/rpc/other/AbstractCasperRpc.ts, src/service/rpc/other/CasperLoadBalancerRpc.ts, src/service/tatum/tatum.other.ts, src/util/constant.ts, src/util/util.shared.ts
=> ALL-5088 - Add Casper rpc

package.json
=> Update version of the package

package.json
=> ALL-9581 - SDK version bump

package.json, packages/api-client/src/lib/models/Currency.ts, packages/shared/core/src/lib/derivation-path.common.ts, packages/shared/core/src/lib/http.common.ts, packages/shared/core/src/lib/models/Blockchain.ts, packages/shared/core/src/lib/models/BlockchainCurrencyMapping.ts
=> ALL-11197 - Add SUI

package.json, src/model/request/Currency.ts
=> ALL-12836: Add unichain.

package.json, packages/api-client/src/lib/models/Currency.ts, packages/shared/core/src/lib/derivation-path.common.ts, packages/shared/core/src/lib/http.common.ts, packages/shared/core/src/lib/models/Blockchain.ts, packages/shared/core/src/lib/models/BlockchainCurrencyMapping.ts
=> ALL-12834: Add Monad.
