tatumio/tatum-js

src/offchain/index.ts
Might want to also double check and see if any other chains are missing from the exports.
=> fix: add missing celo offchain support

src/index.ts
Right now these aren't exported, and you have to directly reference the file to use them
=> export multiToken functions

src/blockchain/tron.ts
This update replaced the wrong endpoint (/v3/tron/current) with the correct one (/v3/tron/info)
=> Used the correct endpoint in `tronGetCurrentBlock`

package.json, src/model/request/Currency.ts
When I use the submodule KCC in core-api, I am getting errors of crashing currency models with @tatumio/tatum.
It seems that others are using the mainjs.
When we change all of the core-api with submodules, I think such things should be considered.
=> add currency KCC

package.json, src/transaction/egld.ts
If the transaction value is greater than or equal to 1000, then after multiplying by 10^18, the toString() function will represent the number in exponential notation (1e+21), which the EGLD REST API does not support
=> fix(egld): proper tx value cast to string

packages/tatum-solana/src/model/request/solana/SolanaNftMetadata.ts
The constants for validating the fields were not quite right. I changed them according to the metaplex token-metadata code. 
Validation code: [Click](https://github.com/metaplex-foundation/metaplex-program-library/blob/408455ddd14764e3e992759ab4258db7a1ffed09/token-metadata/program/src/utils.rs#L40)
Constants: [Click](https://github.com/metaplex-foundation/metaplex-program-library/blob/4f01643bd3931b88bc0e0850334e5cee31996122/token-metadata/program/src/state.rs#L21)
=> fix(solana): nft metadata validation

packages/shared/blockchain/abstract/src/lib/abstract-blockchain.sdk.ts
Adds missing GenerateCustodialWalletBatchPayer (feesCovered) and optional minter to ChainMintErc721. This is also adding minter to mintErc721 (from PLT-908)
=> PLT-396 add missing custodial parameter/interface to generateWalletBatch

package.json, src/wallet/address.spec.ts, src/wallet/address.ts
Removes p2sh btc address option to generate bech32 only, adds version bump
=> PLT-108 - generate bech32 only [V1]

packages/blockchain/bch/src/lib/services/bch.sdk.tx.ts, packages/blockchain/bch/src/lib/utils/bch.address.ts
Due to the error reported in #303, the current decode function is failing and defaults to using `new Address.fromString(address).toLegacyAddress(address)` the right way to call it is without new, so `Address.fromString().toLegacyAddress()` the resulting value returned here sometimes does not work with mainnet.
So updating the `decode` function called in the `toLegacyAddress` to the decode method coming from `cashaddrjs`
=> Updated Decode Function in toLegacyAddress function

CHANGELOG.md, package.json, src/dto/Network.ts, src/dto/rpc/XrpRpcSuite.ts, src/dto/rpc/index.ts, src/e2e/tatum.rpc.xrp.spec.ts, src/service/rpc/engine/XrpRpc.ts, src/service/rpc/engine/index.ts, src/util/util.shared.ts
The point of these changes is to add simple to use interface for interacting with RCP node through our SDK (specifically for most of these methods, only public JSON ones - https://xrpl.org/public-api-methods.html).
=> ALL-1386 XRP RPC calls

README.md
Updated example links on README.md to direct to the adequate location, as visiting v2 and clicking on the example links always ends up with "page not found" and guess this has been a problem to others as it has been to me.
This hasn't been logged as an issue.
=> Updated README.md to update example links (to v2)

CHANGELOG.md, README.md, package.json, src/dto/Currency.ts, src/dto/rpc/index.ts, src/e2e/e2e.util.ts, src/e2e/tatum.address.spec.ts, src/e2e/tatum.fee.spec.ts, src/e2e/tatum.nft.spec.ts, src/e2e/tatum.notification.spec.ts, src/e2e/tatum.rates.spec.ts, src/e2e/tatum.rpc.solana.spec.ts, src/e2e/tatum.rpc.spec.ts, src/e2e/tatum.rpc.tron.spec.ts, src/e2e/tatum.rpc.xrp.spec.ts, src/e2e/tatum.spec.ts, src/e2e/tatum.token.spec.ts, src/service/fee/fee.dto.ts, src/service/fee/fee.ts, src/service/tatum/tatum.ts, src/util/util.shared.ts
- Add fee submodule for Ethereum and Bitcoin chains. 
- Change how TatumSDK instantiates classes for blockchain specific operations. TatumSdk `init` function now returns specific blockchain class with related operations. If the chain does not support a specific module e.g. `rpc` or `fee`, it won't be part of the class.
=> ALL-1688 Add fee submodule

CHANGELOG.md, docs/index.md, docs/rpc.md, package.json
=> ALL-1506 - Fix docs links

CHANGELOG.md, README.md, package.json, src/dto/rpc/EvmBasedRpcInterface.ts, src/dto/rpc/SolanaRpcSuite.ts, src/dto/rpc/TronRpcSuite.ts, src/dto/rpc/UtxoBasedRpcSuite.ts, src/dto/rpc/XrpRpcSuite.ts, src/e2e/rpc/evm.e2e.utils.ts, src/e2e/rpc/tatum.rpc.flare.spec.ts, src/e2e/rpc/tatum.rpc.solana.spec.ts, src/e2e/rpc/tatum.rpc.tron.spec.ts, src/e2e/rpc/tatum.rpc.xrp.spec.ts, src/e2e/rpc/utxo.e2e.utils.ts, src/e2e/tatum.fee.spec.ts, src/e2e/tatum.token.spec.ts, src/service/fee/fee.ts, src/service/rpc/SolanaRpc.ts, src/service/rpc/TronRpc.ts, src/service/rpc/XrpRpc.ts, src/service/rpc/evm/AbstractEvmBasedRpc.ts, src/service/rpc/utxo/AbstractUtxoBasedRpc.ts, src/service/walletProvider/metaMask.ts, src/util/error.ts
Change all RPC methods to return a ResponseDto object with fields: data, status, error. In that way user can get more information about errors if the call fails. This is a breaking change as the actual result of the RPC call will be in the `data` field.
=> ALL-2078 Change all RPC methods to return ResponseDto

src/service/rpc/evm/AbstractEvmBasedRpc.ts
Fixed optional block Number property in eth_getTransactionCount. 
Default state chosen as 'latest'. Discussion is welcome.
=> fix optional blockNumber property in eth_getTransactionCount

.github/workflows/build.yml, .github/workflows/release-pr.yaml, CHANGELOG.md, package.json, src/dto/Network.ts, src/e2e/rpc/evm.e2e.utils.ts, src/e2e/rpc/rpc.e2e.utils.ts, src/e2e/rpc/tatum.rpc.bitcoin.spec.ts, src/e2e/rpc/tatum.rpc.flare.spec.ts, src/e2e/rpc/tatum.rpc.polygon.spec.ts, src/e2e/rpc/tatum.rpc.solana.spec.ts, src/e2e/rpc/tatum.rpc.tron.spec.ts, src/e2e/rpc/tatum.rpc.xrp.spec.ts, src/e2e/tatum.address.spec.ts, src/e2e/tatum.token.spec.ts, src/service/address/address.ts, src/service/rpc/evm/AbstractEvmRpc.ts, src/service/rpc/evm/EvmArchiveLoadBalancerRpc.ts, src/service/rpc/evm/EvmLoadBalancerRpc.ts, src/service/rpc/evm/EvmRpc.ts, src/service/rpc/evm/index.ts, src/service/rpc/generic/LoadBalancerRpc.ts, src/service/rpc/utxo/AbstractUtxoRpc.ts, src/service/rpc/utxo/UtxoLoadBalancerRpc.ts, src/service/rpc/utxo/UtxoRpc.ts, src/service/rpc/utxo/index.ts, src/service/walletProvider/metaMask.ts, src/service/walletProvider/wallet.provider.ts, src/util/util.shared.ts
=> ALL-1512 Archive Non archive calls

README.md
=> Update README.md - Add destroy

CHANGELOG.md, package.json
In Node.js the SDK is not working due to `ReferenceError: fetch is not defined` error
=> Move node-fetch from devDep to Dep

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancerRpc.ts
Extend list of urls for SSRF check. This fixes RPC calls to Horizon EON and Flare
=> ALL-2135 Extend list of urls for SSRF check

CHANGELOG.md, package.json, src/dto/rpc/AbstractJsonRpcInterface.ts, src/service/address/address.ts, src/service/rpc/evm/EvmArchiveLoadBalancerRpc.ts, src/service/rpc/evm/EvmLoadBalancerRpc.ts, src/service/rpc/evm/EvmRpc.ts, src/service/rpc/generic/AbstractBatchRpc.ts, src/service/rpc/generic/LoadBalancerRpc.ts, src/service/rpc/utxo/UtxoLoadBalancerRpc.ts, src/service/rpc/utxo/UtxoRpc.ts
In case of top-level error actually a JsonRpcResponse<any> is returned (not array). Eg. 'method not found'
=> ALL-2134 - fix rawBatchRpcCall return type

CHANGELOG.md, README.md, package.json, src/e2e/e2e.util.ts, src/e2e/extensions/e2e.extensions.ts, src/e2e/extensions/tatum.extensions.spec.ts, src/e2e/rpc/evm/evm.e2e.utils.ts, src/e2e/rpc/evm/tatum.rpc.ethereum.spec.ts, src/e2e/rpc/tatum.rpc.tron.spec.ts, src/e2e/rpc/utxo/tatum.rpc.doge.spec.ts, src/e2e/rpc/utxo/utxo.e2e.utils.ts, src/e2e/tatum.address.spec.ts, src/e2e/tatum.fee.spec.ts, src/e2e/tatum.notification.spec.ts, src/e2e/tatum.rates.spec.ts, src/e2e/tatum.spec.ts, src/service/extensions/tatumsdk.extensions.dto.ts, src/service/tatum/tatum.ts, src/service/walletProvider/metaMask/metamask.wallet.provider.ts
- Extension lifetime management methods made optional to implement.
- Extension lifetime management method destroy() made async and awaited.
- **[BREAKING CHANGE]** `tatumSdk.destroy(): void` was replaced with `tatumSdk.destroy(): Promise<void>`.
=> ALL-2835 - extension lifetime management methods made optional

CHANGELOG.md, package.json, src/e2e/extensions/e2e.extensions.ts, src/e2e/extensions/tatum.extensions.spec.ts, src/service/extensions/tatumsdk.extensions.dto.ts, src/service/tatum/tatum.ts, src/service/walletProvider/metaMask/metamask.wallet.provider.ts
- Extension now has to implement list of supported `Network`.
- **[BREAKING CHANGE]** `TatumSdkExtension` now contains `abstract supportedNetworks: Network[]`.
=> ALL-2835 - enforce network support validation on extensions side

CHANGELOG.md, package.json, src/dto/rpc/EvmBasedRpcInterface.ts, src/e2e/rpc/evm/tatum.rpc.ethereum.spec.ts, src/service/rpc/evm/AbstractEvmRpc.ts
Update debug storage range parameters. The `debugStorageRangeAt` function in the EvmRpc now takes a number instead of a string for the `maxResults` parameter.
=> ALL-2673 Fix debugStorageRangeAt

CHANGELOG.md, README.md, docs/structure.md, package.json, src/e2e/tatum.faucet.spec.ts, src/service/faucet/faucet.dto.ts, src/service/faucet/faucet.ts, src/service/faucet/index.ts, src/service/tatum/tatum.ts
Added submodule `faucet` with method `fund` allowing users to request testnet native tokens from available [Tatum faucets](http://faucets.tatum.io).
:heavy_plus_sign: New feature (non-breaking change which adds functionality)
To request from the faucet, you'll need to specify the network type when initializing your Tatum SDK instance and call `fund` method with wallet address requesting the funds:
```ts
import { TatumSDK, Network, Ethereum } from '@tatumio/tatum'
const tatum = await TatumSDK.init<Ethereum>({
network: Network.ETHEREUM_SEPOLIA,
})
const res = await tatum.faucet.fund('0x712e3a792c974b3e3dbe41229ad4290791c75a82')
if (res.data) {
console.log(res.data)
} else {
console.error(res.error)
}
// Destroy Tatum SDK - needed for stopping background jobs
await tatum.destroy()
```
=> ALL-2946 Add faucet submodule

src/service/address/address.dto.ts, src/service/address/address.ts, src/service/nft/nft.dto.ts
Example fix for REST API - SDK naming mismatch.
Fixes https://github.com/tatumio/tatum-js/issues/965
=> Rename the "last updated block" field of `NftAddressBalance` to match REST API

CHANGELOG.md, package.json, src/e2e/tatum.address.spec.ts, src/service/address/address.ts
Fixes support for UTXO when using `Address.getTransactions` with block ranges
=> UTXO `Address.getTransactions` block ranges support

CHANGELOG.md, package.json, src/dto/shared.dto.ts, src/e2e/tatum.address.spec.ts, src/service/address/address.dto.ts, src/service/address/address.ts, src/service/nft/nft.ts, src/service/token/token.ts
Tezos address balances fixes. Call to `address.getBalance` returns balances of all tokens for a given address. This call accepts only one `address` as a parameter, not an array of addresses.
Update filters for this call to accept optional parameters `tokenTypes`, `page` and `pageSize`
=> ALL-3334 Fix Tezos address balances

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancer.ts, src/util/util.shared.ts
`LoadBalancer` will be checking node statuses in a gentle one by one sort of manner instead of instant Promise blast. 
Also added 2x retry for status checks.
This is an effort to improve stability. In edge case scenarios the LoadBalancing interval call was unfortunate enough to push over RPS limit and marked node as offline while getting 403.
=> ALL-3495 - Improved `LoadBalancer` stability

CHANGELOG.md, package.json, src/service/logger/logger.development.ts, src/util/env.ts, yarn.lock
Assert development environment if `NODE_ENV` is not set. Also changes `TatumDevelopmentLogger` to use globalThis instead of `process.env` for setting `isWelcomeDisabled` flag, so it can be safely used in most environments.
=> Tweak dev env detection

package.json, packages/automation/src/generators/blockchain-evm/files/src/lib/__name__.sdk.ts__template__, packages/automation/src/generators/blockchain-evm/files/src/lib/services/__name__.web3.ts__template__, packages/blockchain/egld/src/lib/__tests__/egld.tx.spec.ts, packages/blockchain/flare/src/lib/flare.sdk.ts, packages/blockchain/flare/src/lib/services/flare.web3.ts, packages/blockchain/polygon/src/lib/polygon.sdk.spec.ts
=> ALL-4358 Update Flare web3

CHANGELOG.md, package.json, src/e2e/tatum.address.spec.ts, src/service/address/address.dto.ts, src/service/address/address.ts
Add option for users to filter transactions by token address. This is applicable only for EVM chains.
=> Add filter tokenAddress to getTransactions

package.json, src/transaction/eth.ts
We don't need call `estimateGas` if the gas property already present in the serialized transaction.
=> Skip gas estimation if already present (ethereum)

CHANGELOG.md, package.json, src/api/api.dto.ts, src/dto/shared.dto.ts, src/e2e/tatum.address.spec.ts, src/service/address/address.dto.ts, src/service/address/address.ts, src/service/nft/nft.dto.ts, src/service/token/token.dto.ts
Improved `getBalance` method in `address` module by introducing `tokenTypes` filter along with `native` option.
=> ALL-6149 Add tokenTypes filter to address getBalance

src/multiToken/multiToken.spec.ts, src/nft/marketplace/auction.spec.ts, src/nft/marketplace/listing.spec.ts, src/nft/nft.spec.ts, src/transaction/polygon.spec.ts
=> ALL-6466: polygon amoy (v1)

CHANGELOG.md, package.json, src/dto/AddressEventNotificationChain.ts, src/e2e/e2e.constant.ts, src/e2e/e2e.util.ts, src/e2e/tatum.notification.spec.ts, src/service/tatum/tatum.evm.ts, src/util/util.shared.ts
=> ALL-6219 - Added AVAX to l1

CHANGELOG.md, package.json, src/e2e/rpc/other/tatum.rpc.kadena.spec.ts, src/service/rpc/other/AbstractKadenaRpc.ts
=> ALL-7310 - Fix Kadena RPC double slash

CHANGELOG.md, src/e2e/rpc/other/tatum.rpc.cardano.rosetta.spec.ts
=> ALL-6920: skip cardano testnet tests

CHANGELOG.md, package.json, src/service/rpc/generic/LoadBalancer.ts
Addition of *.gateway.tatum.io nodes caused ssrf checks to fail and nodes being ignored for routing, relax those checks and allow these nodes no be routed to.
=> ALL-8523: relax ssrf checks and allow tatum gateway nodes

CHANGELOG.md, package.json, src/connector/tatum.connector.ts, src/e2e/e2e.constant.ts, src/e2e/ipfs.spec.ts, src/e2e/rpc/evm/eth/tatum.rpc.beacon.spec.ts, src/e2e/rpc/evm/eth/tatum.rpc.ethereum.spec.ts, src/e2e/rpc/evm/evm.rpc.spec.ts, src/e2e/rpc/other/tatum.rpc.eos.spec.ts, src/e2e/rpc/other/tatum.rpc.solana.spec.ts, src/e2e/rpc/other/tatum.rpc.stellar.spec.ts, src/e2e/rpc/other/tatum.rpc.ton.spec.ts, src/e2e/rpc/other/tatum.rpc.tron.spec.ts, src/e2e/rpc/utxo/utxo.rpc.spec.ts, src/e2e/tatum.rates.spec.ts, src/e2e/tatum.spec.ts, src/service/rpc/generic/LoadBalancer.ts, src/util/network.utils.ts
Fixing following reported issue:
https://github.com/tatumio/tatum-js/issues/1132
=> ALL-9108 Fix tatum connector undefined error

package.json, packages/api-client/src/lib/models/Currency.ts, packages/blockchain/base/src/lib/__tests__/base.nft.spec.ts, packages/blockchain/optimism/src/lib/__tests__/optimism.nft.spec.ts, packages/shared/core/src/lib/contract.common.ts, packages/shared/core/src/lib/models/BlockchainCurrencyMapping.ts
Rename existing currencies ARB & BASE & OPTIMISM to ETH_ARB & ETH_BASE & ETH_OP
Add new currencies USDC_ARB, USDT_ARB, USDC_BASE, USDT_BASE, USDC_OP, USDT_OP
Fix BASE and OPTIMISM unit tests, where Currency was passed instead of chain and now currency has different string value and does not match chain.
=> ALL-9443 Renamed Currency.ARB BASE OPTIMISM & Added USDC USDT for ARB BASE OPTIMISM

package.json, tools/patches/bitcore-lib+10.8.0.patch, yarn.lock
Updated the `bitcore-lib` library to enable support for the bitcoin taproot addresses.
=> ALL-4487: update 'bitcore-lib' for bitcoin taproot address support
